Feature/50 navigation
Canato/Purity-Test pull request #51
Opened 2020-11-24 17:39 UTC by tomklecha

implementation of navigation component for all features

2020-11-25 01:05 UTC, Canato requested changes
Please return `.idea/codeStyles/` folder so we can enforce the ktlint code style

Thanks for cleaning the rest

- Delete features/home/consumer-rules.pro
- Delete features/home/proguard-rules.pro

Last note, I'm having the feeling that Ktlint didn't check this code 🤔 
Maybe is because you removed codeStyleConfig, many errors, missing lines etc

2020-11-25 01:05 UTC, Canato commented on features/home/src/androidTest/java/com/can_apps/home/HomeFragmentTest.kt
> +        assertEquals(navController.currentDestination?.id, R.id.questionsFragment)
declare the variables on the begin
```
val expectedFragment = R.id.questionsFragment
val viewMatcher = ViewMatchers.withId(R.id.questionButton)
val performAction = ViewActions.click()
```

2020-11-25 01:05 UTC, Canato commented on features/home/src/main/res/layout/fragment_home.xml
> +        android:text="Hello World!"
.

2020-11-25 01:05 UTC, Canato commented on features/home/src/main/res/values/colors.xml
> +</resources>
Do we need this inside home only? How about we add into common module?

2020-11-25 01:05 UTC, Canato commented on features/home/src/main/res/values/strings.xml
> +    <string name="questions_text">Questions</string>
Common module

2020-11-25 17:17 UTC, tomklecha commented on features/home/src/androidTest/java/com/can_apps/home/HomeFragmentTest.kt
> +        assertEquals(navController.currentDestination?.id, R.id.questionsFragment)
you are right

2020-11-25 17:26 UTC, tomklecha commented on app/src/main/java/com/can_apps/purity_test/MainActivity.kt
> +        val navHostFragment = supportFragmentManager.findFragmentById(R.id.my_nav_fragment) as NavHostFragment?
i saw in your project that you were using nullable value, I was confused so I reused it. Change to non null

2020-11-25 17:26 UTC, tomklecha commented on app/src/main/java/com/can_apps/purity_test/MainActivity.kt
> +        val navController = navHostFragment!!.navController
changed

2020-11-25 17:26 UTC, tomklecha commented on app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
thank you !

2020-11-25 17:26 UTC, tomklecha commented on features/home/src/main/AndroidManifest.xml
> +    /
done

2020-11-25 17:27 UTC, tomklecha commented on features/home/src/androidTest/java/com/can_apps/home/HomeFragmentTest.kt
> +internal class HomeFragmentTest {
please check #53 to resolve it

2020-11-25 17:27 UTC, tomklecha commented on features/home/src/androidTest/java/com/can_apps/home/HomeFragmentTest.kt
> +        assertEquals(navController.currentDestination?.id, R.id.questionsFragment)
changed

2020-11-25 17:27 UTC, tomklecha commented on features/home/src/main/res/layout/fragment_home.xml
> +        android:text="Hello World!"
shame on me

2020-11-25 17:27 UTC, tomklecha commented on features/home/src/main/res/values/colors.xml
> +</resources>
was not sure, currently in common

2020-11-25 17:28 UTC, tomklecha commented on features/home/src/main/res/values/strings.xml
> +    <string name="questions_text">Questions</string>
as above

2020-11-25 22:00 UTC, Canato commented on app/src/main/java/com/can_apps/purity_test/MainActivity.kt
> +        val navHostFragment = supportFragmentManager.findFragmentById(R.id.my_nav_fragment) as NavHostFragment?
I did ask our suggest a change, I make a question =D

I keep my question

2020-11-25 22:26 UTC, tomklecha commented on app/src/main/java/com/can_apps/purity_test/MainActivity.kt
> +        val navHostFragment = supportFragmentManager.findFragmentById(R.id.my_nav_fragment) as NavHostFragment?
? means that value might be null, so support fragment manager could be null in some case, if maybe view would not be created

2020-11-25 22:27 UTC, tomklecha commented on features/home/src/main/res/layout/fragment_home.xml
> +        android:text="Hello World!"
can be resolved ?

2020-11-26 00:28 UTC, Canato approved these changes

2020-11-26 09:01 UTC, merged