updated QuestionsContract.kt
Canato/Purity-Test pull request #61
Opened 2021-02-07 15:25 UTC by tomklecha

2021-02-07 15:47 UTC, Canato requested changes

2021-02-07 15:47 UTC, Canato commented on features/questions/src/main/java/com/can_apps/questions/core/QuestionsContract.kt
> +        fun onItemClicked(modelId: QuestionIdModelEnum)
Nice

2021-02-07 15:47 UTC, Canato commented on features/questions/src/main/java/com/can_apps/questions/core/QuestionsContract.kt
> +        fun onFinishTestPressed()
Not need, we can check that is the last category from `fun fetchNextCategoryQuestions()` 

We could change to `onNextPressed()` and this would do both cases, getNextCategory or go to result flow if there is not next category.

2021-02-07 15:47 UTC, Canato commented on features/questions/src/main/java/com/can_apps/questions/core/QuestionsContract.kt
> +        fun showResult(score: List<QuestionsModelDetails>)
If I remember right, this is not the screen that will show the result. So we need some method to be more specific. like
`goToResultScreen` or  `navigateToResult` 

What you think?

2021-02-07 16:51 UTC, tomklecha commented on features/questions/src/main/java/com/can_apps/questions/core/QuestionsContract.kt
> +        fun showResult(score: List<QuestionsModelDetails>)
yes, naming convention should be better, will change, I agree

2021-02-07 16:55 UTC, tomklecha commented on features/questions/src/main/java/com/can_apps/questions/core/QuestionsContract.kt
> +        fun onFinishTestPressed()
Agree and disagree -> 
agree -> yes, we could implement is in the flow
disagree -> we give more functionality into fetching method - return first, return next, return result? too much
currently method looks like this
`override suspend fun retrieveQuestionsDomain(
        categoryId: String?
    ): QuestionsDetailsDomain? =
        when (questions.isEmpty()) {
            true -> {
                questions = repository.retrieveList()
                questions.first()
            }
            else -> {
                val actualIndex = questions.indexOfFirst { it.category.name == categoryId }

                if (actualIndex == -1 || actualIndex == questions.size) null
                else questions[actualIndex + 1]
            }
        }`
        instead with this method, since we already changed the implementation of receiving the new categories, that would be much simpler to test, instead of adding on top. New method makes it simpler

2021-02-07 18:05 UTC, Canato commented on features/questions/src/main/java/com/can_apps/questions/core/QuestionsContract.kt
> +        fun onFinishTestPressed()
> we give more functionality into fetching method

This is not the fetching method, this method is inside the interactor. 

> return first, return next, return result

This is about the interactor method, I believe. Cause the presenter method should not return anything.

So let's talk about the method. 
`suspend fun retrieveQuestionsDomain(categoryId: String?): QuestionsDetailsDomain?` 

This method has only one responsibility. Return next questions or null.

Literally in the code we have:
```
model?.let {
    showList(it)
    if (it.isLastCategory.value) setNewActionButtonFunction()
} // ?: Go to results screen, nothing else to show
```

We have a comment for this ^^ 

So we don't need to make any change in the interactor. What is good. 
And even more, we don't need to hide/show button on the view or the change the clickListener in the view to change which presenter call to make.

we just need to change this comment /\ 
from `} // ?: Go to results screen, nothing else to show`
to
```
} ?: run {
    view?.showResult(...)
}
```

If still a little strange for you, let's have a talk, maybe I'm missing something 🤔

2021-02-08 06:41 UTC, tomklecha commented on features/questions/src/main/java/com/can_apps/questions/core/QuestionsContract.kt
> +        fun onFinishTestPressed()
ok, tested your comment. Now with playing a bit I am happy to go with your version.
Side note - we have weak tests on interactor side. If you click last element, instead of returning null is returning error - wrong index size. To make things work i needed to change
`if (actualIndex == -1 || actualIndex == questions.size) null else questions[actualIndex + 1] } }` 
to
`if (actualIndex == -1 || actualIndex == questions.size - 1) null else questions[actualIndex + 1] } }`
then it is doing what expected. But tests are passing with both conditions. So I will write up some tests around it extra

2021-02-08 09:30 UTC, Canato commented on features/questions/src/main/java/com/can_apps/questions/core/QuestionsContract.kt
> +        fun onFinishTestPressed()
good catch!

2022-04-26 19:47 UTC, closed without merging