Feature - Jetpack compose setup
Canato/Purity-Test pull request #68
Opened 2022-05-20 01:24 UTC by lucasvillaverde

## Jetpack Compose Setup
- Downgrading Kotlin to 1.6.10 (Maximum supported for Compose)
- Creating a Home Screen Sample using Compose
- Organizing libraries versions

<img width="229" alt="image" src="https://user-images.githubusercontent.com/35536098/169430012-3925c6fc-2c65-467c-89c9-be8904377bf9.png">

2022-05-20 01:26 UTC, lucasvillaverde commented on app/src/main/AndroidManifest.xml
> +            android:exported="true">
Now its mandatory:
```
As of Android 12, android:exported must be set; 
use true to make the activity available to other apps, and false otherwise.
For launcher activities, this should be set to true
```

2022-05-20 09:04 UTC, Canato requested changes
remove the `./idea/` folder stuff ;)

2022-05-20 09:04 UTC, Canato commented on features/home/src/main/java/com/can_apps/home/app/HomeScreen.kt
> +fun HomeScreenPreview() {
private

2022-05-28 15:35 UTC, lucasvillaverde commented
> remove the `./idea/` folder stuff ;)

You mean.. deleting all the folder or discard the changes and add to those files to gitignore?

2022-05-30 08:08 UTC, Canato commented
> > remove the `./idea/` folder stuff ;)
> 
> You mean.. deleting all the folder or discard the changes and add to those files to gitignore?

Remove the changes and add to gitignore please

2022-05-31 00:37 UTC, lucasvillaverde commented
> > > remove the `./idea/` folder stuff ;)
> > 
> > 
> > You mean.. deleting all the folder or discard the changes and add to those files to gitignore?
> 
> Remove the changes and add to gitignore please

Since we've upgraded our kotlin and gradle version (as well as the plugin version) we should maintain the gradle.xml file in order to prevent the following error:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/35536098/171071590-6985bf5e-d972-4bd5-bc73-5085118433b1.png">

2022-05-31 08:46 UTC, Canato approved these changes

2022-05-31 08:47 UTC, merged